### ISSUE TITLE
Implement basic design

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-app-budget-item#1]
This app is supposed to provide information on a single budget item (be it a top-level, 2 digit item or an 8-digit TAKANA).

The basic layout consists of a
1. title,
2. textual area with dynamically generated text
3. analysis area with multiple tabs, each showing a different aspect or visualisation of the item.

The basic design can be seen here: https://projects.invisionapp.com/d/main#/console/7587193/166401746/preview

For now the task is to implement bullets (1) and (2) from above.

**Comment by naamac** [comment]
@akariv I can't push :/

**Comment by akariv** [comment]
@naamac you got it now.. my bad

**Comment by akariv** [comment]
This design is scrapped for now :(
